[tool.poetry]
name = "potnia"
version = "0.1.0"
description = "Potnia is a Python Library to help users work with Aegean scripts."
authors = ["Emily Tour <esmtour@gmail.com>", "Robert Turnbull"]
license = "Apache-2.0"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^6.0.1"
attrs = "^23.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
